### ISSUE TITLE
API for queries

### ISSUE THREAD

**Issue by lex-lex** [normativeai/backend#11]
As a next step, queries need to be included into back- and front end. What methods do we need?

- Create/delete/modify query
- Execute query

Queries consist of
- name
- description
- theory context
- assumptions
- goal

Anything else?

**Comment by shaolintl** [comment]
I just added all this functionality as well as the lastUpdate field. Note that assumptions is an array. I cannot think of anything else right now. You can have a look on test/fixturres/query.js for examples of successful and non-successful queries. The working one is with regard to Theory in test/fixturres/theory.js

**Comment by shaolintl** [comment]
This information should be sen using the relevant theory id, i.e. query.theory = theory.id

**Comment by lex-lex** [comment]
Ah okay, I did not see that in the test case (resp. I did not understand it :) )

**Comment by shaolintl** [comment]
I probably didnt write it there :) The tests are not that good.
