### ISSUE TITLE
Response of PUT /api/theories/id

### ISSUE THREAD

**Issue by lex-lex** [normativeai/backend#14]
Current, PUT `api/theories/id` just gives "Theory updated" as plain text response. Could you changed it in such a way that

1. the API call returns a JSON object that has the property `message` (which contains this "Theory updated" message)
2. the response JSON object additionally contains the new "last update" time of the theory (as this might not agree with the client-side time of the save request and users might use this information. however, after reloading the theory, this information is served from the back end and thus might be different from a locally computed one)

One could think of structuring the JSON response objects s.t. they always have the field `message` and the field `data` (if any auxiliary data), e.g. in this case `{message: 'Theory updated', data: {lastUpdate: time}}`. This would also be useful for any other API responses. What do you think?

**Comment by shaolintl** [comment]
Sure, its a good idea. I will go over all replies and use this format.

**Comment by shaolintl** [comment]
The response optional fields are:
message - for positive messages
err - for negative message
errors - an array of objects with location, param, message and value which should be used for specific errors when filling in a form, for example, if the user password is empty, then you will get:
{ errors:
       [ { location: 'body', param: 'password', msg: 'password required', value: '' }]
}
