### ISSUE TITLE
Get list of all theories

### ISSUE THREAD

**Issue by lex-lex** [normativeai/backend#19]
Hi Tomer,

is there a method to get a summary/list of all available theories (not just by the current user)? If I understand the test cases of the back end, `api/theories` will just return a summary of the theories of the current user. However, for normativeai/frontend#12 I will need to get a list of all available theories for cloning. Can you implement that?

**Comment by shaolintl** [comment]
We have talked about having the ability to return all theories which correspond to some keyword or tag. I.e. one can use tags in the description of theories (@tag privacy-law) and then you can retrieve all theories with this tag
GET /api/theories/find?query=blah

The query is a regex.

**Comment by shaolintl** [comment]
GET /api/theories/find?query=privacy-law

**Comment by shaolintl** [comment]
Please tell me if this functionality is not enough.

**Comment by lex-lex** [comment]
What is returned for `GET /api/theories/find?query=`, i.e. the empty search string?

**Comment by shaolintl** [comment]
You are right. Using the regular expression `.*` should return everything. `
GET /api/theories/find?query=.*`
