### ISSUE TITLE
Filter "only active facts" for running queries and consistency check

### ISSUE THREAD

**Issue by lex-lex** [normativeai/backend#21]
Related to normativeai/frontend#16: The front-end now includes a property `active` (either `true` of `false` as Booleans) for each fact, additional to the old fields such as `original`, `formula` etc; and will send this to the back-end while saving theories. Graphically, each "not active" fact is blurred out in the front-end. On the back-end, this needs to be reflected during execution of queries and consistency checks: Only facts that are `active` should be included for this, i.e. passed to the prover in the end.

For the moment (until the active field is included in the back-end), the front-end will of course graphically interpret every fact as disabled (as there is no `active: true`).

**Comment by shaolintl** [comment]
It also supports backward compatibility and will deactivate a fact only if it is defined as false
