### ISSUE TITLE
Supporting independency checking of facts

### ISSUE THREAD

**Issue by shaolintl** [normativeai/backend#22]
A useful feature is to be able to infer if a certain fact follows from the others and is therefore dependent. This can be obtained by trying to prove this fact based on all other active facts.

**Comment by lex-lex** [comment]
Did anyone test this feature yet?

**Comment by shaolintl** [comment]
I did lightly. More serious testing is needed though

**Comment by shaolintl** [comment]
Anyway, it was added so any mulfunctioning should be added as a bug
