### ISSUE TITLE
Change mleancop timeout messages to give more information

### ISSUE THREAD

**Issue by shaolintl** [normativeai/backend#27]
Right now, it reports a server error. We should assume that timeout happens mainly on failing to prove and report a more informative messages as follows:
- on consistency checking - "Backend prover timeout - Please note that this normally indicates that the consistency check should succeed"
- on proving a query - "Backend prover timeout - Please note that this normally indicates that the goal is not derivable from the assumptions and the theories 

@lex-lex Right now we have green, red and blue colors. Should we have a yellow one for these kinds of message? Which JSON object should I return?

**Comment by lex-lex** [comment]
The information alerts use the bootstrap style names for coloring, e.g. "warning" is yellow, "danger" is red, "success" is green, "info" is blue. If you want to decide the color of the response from the back end side, I'd suggest you include this information in the response, e.g. using an additional attribute `type` in the JSON.

What do you think?

**Comment by shaolintl** [comment]
@lex-lex Good idea. I have implemented it for now only for consistency and independence of theories and norms. You will get error code 206 and json {message, type}. Once you implement it and it works, I will do it also for queries.

**Comment by shaolintl** [comment]
@lex-lex I reverted the change as right now it breaks consistency and independence checks. I have moved the change to branch timeout so you can test it.

**Comment by lex-lex** [comment]
@shaolintl Could you please merge it into master s.t. I can test it without switching back and forth between different back end version? Just don't update nai.uni.lu as long as the front end is not compatible.

**Comment by shaolintl** [comment]
@lex-lex The update from master is automatic. Should I create a branch development which will contain the latest code and against which you will keep working?

**Comment by lex-lex** [comment]
Sounds reasonable, thanks!

**Comment by shaolintl** [comment]
@lex-lex Ok, the branch is called dev and will always contain the latest pushed code.

**Comment by lex-lex** [comment]
Ok, messages are included. You can merge that feature into master now.

**Comment by shaolintl** [comment]
In fact, I did that already by mistake..

**Comment by lex-lex** [comment]
Also, I locally merged the master before into dev because the vocabulary was not included in dev. just fyi :)

**Comment by lex-lex** [comment]
So this is resolved?

**Comment by lex-lex** [comment]
It seems that the answers of the back end are not consistently using the proposed format. When doing e.g. a successful independence check, it will just return `{data: {independent: true}}` which will not be interpreted correctly as it does not contain `message` and `type`. Can you update this?

**Comment by shaolintl** [comment]
Fixed, sorry. I misunderstood but it makes lots of sense.
