### ISSUE TITLE
Include vocabulary (both auto and manual) in query GET

### ISSUE THREAD

**Issue by lex-lex** [normativeai/backend#28]
When getting a query, `GET /api/queries/id`, could you please include the vocabulary of the chosen theory (if chosen) in the result?
More detailed: The result of the above GET, say `result`, contains a field `result.theory`  which contains the theory id, theory description, theory name, etc. Could you add here also the voc?

I can use this for a list of defined vocabulary for annotating the query parts (no new vocabulary to be allowed here).

**Comment by shaolintl** [comment]
Associated theory is returned with the two fields - auto and normal voc
