### ISSUE TITLE
Annotated term in query 2 is not appearing in formalization

### ISSUE THREAD

**Issue by terezanovot** [normativeai/backend#35]
In query 2, only one annotated term appears in formalization, but the other one doesn't.

**Comment by lex-lex** [comment]
Oh ok, I thought the idea of complex annotations (i.e. using connectives) was to avoid single terms with complex meaning. Also, the GUI will not represent it graphically that it in fact is not just a "piece of vocabulary". I think this might cause confusions, but I am not a GUI designer – so at is well :-) 
Also, there is no way to forbid it; we should maybe just not advertise it.

**Comment by shaolintl** [comment]
I agree. It should not be used normally. @terezanovot It is better to avoid using this "feature" right now.
