### ISSUE TITLE
rename connectives

### ISSUE THREAD

**Issue by Gauntlet173** [normativeai/backend#39]
"permission if" and "permission only if" sound like the difference between implication and bi-directional implication, and don't make their actual distinction clear. Perhaps they should be renamed "if ___ permission ____" and "permission ____ if ____" in the interface.

**Comment by shaolintl** [comment]
@Gauntlet173 I have followed your renaming for all connectives. Please check and reopen if there are still problems.

**Comment by Gauntlet173** [comment]
I mentioned in email that I agree with Tereza it is confusing-looking. I think we should go with shorter names, and consider using the text with blanks as a tool-tip when you hover your mouse over the name?
