### ISSUE TITLE
User token valid after /logout

### ISSUE THREAD

**Issue by lex-lex** [normativeai/backend#4]
After (successfully) sending GET `api/logout`, the user token still seems valid as `api/theories` returns the expected result (as for logged in users).

**Comment by shaolintl** [comment]
Apparently, it is impossible to delete a token on the server side once it was created. It is only possible to expire it. This means that logout should be handled by the client by deleting the token.

https://medium.com/devgorilla/how-to-log-out-when-using-jwt-a8c7823e8a6

**Comment by lex-lex** [comment]
Ok, this is what I do on the client side anyway. Is there then any use in calling `/logout`, after all?

**Comment by shaolintl** [comment]
Right now, no. But it might be a good idea to call it anyway. Maybe we will think of other things which can be done on the server side.
