### ISSUE TITLE
api/theories returns unexpected format

### ISSUE THREAD

**Issue by lex-lex** [normativeai/backend#6]
When calling `api/theories` (with id or without for all theories), the return JSON does not contain the fields `content`, `vocabulary` and `formalization` as they should according to the test supplied in `test/theory.js`. They do contain the other information, though.

**Comment by shaolintl** [comment]
The test requires only the mentioned fields and it follows your requirements email. I do realize that at least the theoryById should return everything. What about the one which returns all theories?

**Comment by lex-lex** [comment]
Yes, you are right; only theoryById needs to give these information – I see no point in having the information included in the universal query.

**Comment by shaolintl** [comment]
This is what I get in the response of the exact same query:
{"_id":"5c287fad512c9c3eaa4d25c0","name":"Test title 4","lastUpdate":"2018-12-30T08:19:57.681Z","description":"Desc plah plah 4","content":"Content","vocabulary":[{"_id":"5c287fad512c9c3eaa4d25c2","symbol":"D","original":"Delivery"},{"_id":"5c287fad512c9c3eaa4d25c1","symbol":"I","original":"Insurance"}],"formalization":[{"_id":"5c287fad512c9c3eaa4d25c3","original":"Delivery means you should make Insurance","formula":"D => I"}]}~/work/

**Comment by lex-lex** [comment]
That's odd. I cannot reproduce this. I pulled the latest version to the back end and recompiled it. 
My request is:
```
GET /api/theories/5c287fad512c9c3eaa4d25c0 HTTP/1.1
Host: localhost:3000
Connection: keep-alive
Accept: application/json, text/plain, */*
Origin: http://localhost:8887
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVjMDI4ODQwMGNlMjdhMjI0OGQ3MTZhOCIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSJ9LCJpYXQiOjE1NDYxNTc4Mzh9.4RPmOwxbgfMi9WVKUML_eUR7LLakCtZQdjArftCsxF0
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,de;q=0.8
If-None-Match: W/"81-+qZTe5t2smNTN6/DhAOMmSl5nto"
```
The response header is:
```
HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 129
ETag: W/"81-+qZTe5t2smNTN6/DhAOMmSl5nto"
Date: Sun, 30 Dec 2018 13:28:57 GMT
Connection: keep-alive
```
with response:
```
{"_id":"5c287fad512c9c3eaa4d25c0","name":"Test title 4","lastUpdate":"2018-12-30T08:19:57.681Z","description":"Desc plah plah 4"}
```

Any ideas?

**Comment by shaolintl** [comment]
The change was in a later commit: 56aaa6477d9c
