### ISSUE TITLE
Switch api protocol to https

### ISSUE THREAD

**Issue by lex-lex** [normativeai/backend#7]
We should sooner or later (preferrably sooner, I guess) switch to https for the API calls. In particular since passwords during log-in are transmitted in plain text; transport encryption should be used. This seems to be common best practice (i.e. to transmit plain text password but using SSL/https).

**Comment by shaolintl** [comment]
I am fine with that and can change the server to work with https easily but we probably need to open a ticket for installing an ssl certificate, etc. I think we can move it to after the publication but before the tutorial, if it takes place.

**Comment by shaolintl** [comment]
@lex-lex Just occurred to me, if the two servers are on the same machine, we dont really need the backend to support https, no? Only the frontend.

**Comment by lex-lex** [comment]
Obsolete as already addressed by the uni.lu servers.
